efaults: &defaults
  working_directory: ~/lf-code-challenge
  docker:
    — image: circleci/openjdk:8-jdk-stretch

version: 2.1
orbs:
  gradle: bizzabo/gradle@1.1.0
jobs:
  build:
    <<: *defaults

    steps:
      - checkout

      - run: ./gradlew build