version: 2 # use CircleCI 2.0
jobs: # a collection of steps
  build:
    docker: # run the steps with Docker
      - image: circleci/openjdk:8-jdk # ...with this image as the primary container; this is where all `steps` will run
    steps: # a collection of executable commands
      - checkout # check out source code to working directory

      - run:
          name: Build JAR file # See: https://circleci.com/docs/2.0/parallelism-faster-jobs/
          command: ./gradlew build

      - run:
          name: Run unit tests # See: https://circleci.com/docs/2.0/parallelism-faster-jobs/
          command: ./gradlew test

      - run:
          name: Send to CodeCov # See: https://circleci.com/docs/2.0/parallelism-faster-jobs/
          command: bash <(curl -s https://codecov.io/bash -c -F unittests)


workflows:
  version: 2
  workflow:
    jobs:
      - build